export const DATA = [{
    imdb_id: "tt0499549",
    "Id": 19995,
    "movieId": 19995,
    "Genre":
        "Action, Adventure, Fantasy, Science Fiction", 
        "Director": "James Cameron", 
        "Actor": "Sam Worthington, Zoe Saldaña, Sigourney Weaver", 
        "Title": "Avatar", "Duration": 162, "Release": "2009", "Description": "In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.", "Rating": 112.693, "Trailer": "https://www.youtube.com/watch?v=LgZ2MDuJvhc", "Country": "United States", "Thumbnail": "https://image.tmdb.org/t/p/w300_and_h450_bestv2/kyeqWdyUXW608qlYkRqosgbbJyK.jpg", "Cover": "https://media.themoviedb.org/t/p/w533_and_h300_bestv2/vL5LR6WdxWPjLPFRLe133jXWsh5.jpg", "Watch": "https://vidsrc.xyz/embed/movie/19995"
},
{
    imdb_id:
        "tt0497595", "Id": 1096978, "movieId": 1096978, "Genre": "Drama", "Director": "Lluís Quílez", "Actor": "Sebastián Haro, Rosana Pastor, Gerard Villegas", "Title": "Avatar", "Duration": 15, "Release": "2006", "Description": "Tension mounts between a quadraplegic man and his wife as she prepares a bath for him.", "Rating": 8.688, "Trailer": "", "Country": "Spain", "Thumbnail": "https://image.tmdb.org/t/p/w300_and_h450_bestv2/gmnD2e1RvMdCl9D1rsDEQaQlJxK.jpg", "Cover": "https://media.themoviedb.org/t/p/w533_and_h300_bestv2/pzgzH4LJoFmQKVPgKs0VZPWUoFZ.jpg", "Watch": "https://vidsrc.xyz/embed/movie/1096978"
},
{ imdb_id: "tt1900832", "Id": 278698, "movieId": 278698, "Genre": "Documentary", "Director": "Kurt Mattila", "Actor": "Bryan Konietzko, Michael Dante DiMartino, Benjamin Wynn", "Title": "Avatar Spirits", "Duration": 32, "Release": "2010", "Description": "Bryan Konietzko and Michael Dante DiMartino, co-creators of the hit television series, Avatar: The Last Airbender, reflect on the creation of the masterful series.", "Rating": 7.52, "Trailer": "", "Country": "", "Thumbnail": "https://image.tmdb.org/t/p/w300_and_h450_bestv2/oBWVyOdntLJd5bBpE0wkpN6B6vy.jpg", "Cover": null, "Watch": "https://vidsrc.xyz/embed/movie/278698" },
{ imdb_id: "tt1778212", "Id": 183392, "movieId": 183392, "Genre": "Documentary", "Director": "Laurent Bouzereau", "Actor": "James Cameron, Sam Worthington, Zoe Saldaña", "Title": "Capturing Avatar", "Duration": 98, "Release": "2010", "Description": "Capturing Avatar is a feature length behind-the-scenes documentary about the making of Avatar. It uses footage from the film's development, as well as stock footage from as far back as the production of Titanic in 1995. Also included are numerous interviews with cast, artists, and other crew members. The documentary was released as a bonus feature on the extended collector's edition of Avatar.", "Rating": 15.744, "Trailer": "", "Country": "United States", "Thumbnail": "https://image.tmdb.org/t/p/w300_and_h450_bestv2/26SMEXJl3978dn2svWBSqHbLl5U.jpg", "Cover": "https://media.themoviedb.org/t/p/w533_and_h300_bestv2/axSaeKvV5xF3zGYwXaSF8rUxaO1.jpg", "Watch": "https://vidsrc.xyz/embed/movie/183392" },
{ imdb_id: "tt1613763", "Id": 100287, "movieId": 100287, "Genre": "Documentary, Science Fiction", "Director": "Bente Milton, Mikkel Stolt", "Actor": "Mikkel Stolt, Rob Gould, Helena Kirkorian", "Title": "My Avatar and Me", "Duration": 0, "Release": "2010", "Description": "is a creative documentary-fiction film and a film that might expand your sense of reality. It is the story about a man who enters the virtual world Second Life to pursue his personal dreams and ambitions. His journey into cyberspace becomes a magic learning experience, which gradually opens the gates to a much larger reality.", "Rating": 3.731, "Trailer": "", "Country": "", "Thumbnail": "https://image.tmdb.org/t/p/w300_and_h450_bestv2/dZCj0jiOoDzAzbQM7ryYFEjkjs7.jpg", "Cover": null, "Watch": "https://vidsrc.xyz/embed/movie/100287" },
{ imdb_id: null, "Id": 993545, "movieId": 993545, "Genre": "Music", "Director": "Gautier & Leduc", "Actor": "Johannes Eckerström, Jonas \"Kungen\" Jarlsby, Tim Öhrström", "Title": "Avatar - Au Hellfest 2022", "Duration": 0, "Release": "2022", "Description": "", "Rating": 0.564, "Trailer": "", "Country": "", "Thumbnail": "https://image.tmdb.org/t/p/w300_and_h450_bestv2/fw6cPIsQYKjd1YVQanG2vLc5HGo.jpg", "Cover": "https://media.themoviedb.org/t/p/w533_and_h300_bestv2/cACUWJKvRfhXge7NC0xxoQnkQNu.jpg", "Watch": "https://vidsrc.xyz/embed/movie/993545" },
{
    imdb_id: "tt0476734", "Id": 926519, "movieId": 926519, "Genre":
        "Comedy", "Director": "Jeanne Barbillon", "Actor": "Bernadette Lafont, Louis Mercuret", "Title": "The Botanical Avatar of Mademoiselle Flora", "Duration": 14, "Release": "1965", "Description": "A young woman lives sadly in a small garrison town with a soldier. Little by little, won over by boredom, sadness, total inaction, she develops a relationship with plants and starts talking to plants.", "Rating": 4.22, "Trailer": "https://www.youtube.com/watch?v=0aRC-0VPT7o", "Country": "France", "Thumbnail": "https://image.tmdb.org/t/p/w300_and_h450_bestv2/jV7LWoQbwXplgdIbMvT4UB8O1E3.jpg",
    "Cover": null, "Watch": "https://vidsrc.xyz/embed/movie/926519"
}]